# Select image from https://hub.docker.com/_/php/
image: php:7.2

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

services:


variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)


test:php71:
  image: php:7.1
  script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml.dist --coverage-text

# We test PHP7 with MySQL, but we allow it to fail
test:php72:
  image: php:7.2
  script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml.dist --coverage-text