language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - rm composer.lock

install:
  - sudo apt-get install parallel
  - composer install --dev --prefer-dist

before_script:
  - mkdir -p build/coverage

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run --config-file ./.php_cs
  - php tests/run-tests.php --clover ../build/logs/clover.xml

after_script:
  # Merges the individual clover reports of each component into a single clover.xml
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
