language: php

php:
  - 5.5
  - 5.4
  - hhvm

install:
  - composer install

script:
  - ./vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-html ./tests/report

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm