language: php

php:
  - 5.5
  - 5.4
  - hhvm

install:
  - sudo apt-get install parallel
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-html

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm